services:
  gym-pass-like-database:
    image: bitnami/postgresql:latest
    container_name: gym-pass-like-database
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apisolid
    ports:
      - "5432:5432"
